br.com.fiap.admin:
  name: ${ADMIN_NAME:admin}
  cpf: ${ADMIN_CPF:000.000.000-00}
  email: ${ADMIN_EMAIL:admin@local}
  password: ${ADMIN_PASSWORD:admin123}
  role: ${ADMIN_ROLE:ROLE_ADMIN}

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
springdoc:
  api-docs:
    enabled: ${SPRINGDOC_API_DOCS_ENABLED:true}
    path: /v3/api-docs
  swagger-ui:
    enabled: ${SPRINGDOC_SWAGGER_UI_ENABLED:true}
    path: /swagger-ui.html
server:
  port: ${SERVER_PORT:8080}

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://db:5432/soat7}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:postgres}
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:validate}
    open-in-view: false
  flyway:
    enabled: ${FLYWAY_ENABLED:true}
    locations: classpath:db/migration

carstore:
  view:
    base-url: ${CARSTORE_VIEW_BASE_URL:http://host.docker.internal:8081}


security:
  jwt:
    issuer: ${JWT_ISSUER:carstore-core}
    private-key-path: ${JWT_PRIVATE_KEY_PATH:./keys/private_key.pem}
    public-key-path: ${JWT_PUBLIC_KEY_PATH:./keys/public_key.pem}

