br.com.fiap.admin:
  name: ${ADMIN_NAME:admin}
  cpf: ${ADMIN_CPF:000.000.000-00}
  email: ${ADMIN_EMAIL:admin@local}
  password: ${ADMIN_PASSWORD:admin123}
  role: ${ADMIN_ROLE:ROLE_ADMIN}

springdoc:
  api-docs:
    enabled: ${SPRINGDOC_API_DOCS_ENABLED:false}
    path: /v3/api-docs
  swagger-ui:
    enabled: ${SPRINGDOC_SWAGGER_UI_ENABLED:false}
    path: /swagger-ui.html
server:
  port: ${SERVER_PORT:8080}

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:validate}
    open-in-view: false
  flyway:
    enabled: ${FLYWAY_ENABLED:true}

carstore:
  view:
    base-url: ${VIEW_BASE_URL}

security:
  jwt:
    issuer: ${JWT_ISSUER:carstore-core}
    private-key-path: ${JWT_PRIVATE_KEY_PATH:/app/keys/private_key.pem}

